### ISSUE TITLE
May I ask if it is possible to publish the processed DDD dataset？

### ISSUE THREAD

**Issue by YangxinCs** [yuanxiao1988/Benchmarking-of-Phenotype-driven-Gene-Prioritization-Methods#1]
The raw data on the EGA official website is too large for me to process, and I sincerely hope you can help me

**Comment by yuanxiao1988** [comment]
Hi, what can I do for you

**Comment by yuanxiaoprc** [comment]
> The raw data on the EGA official website is too large for me to process, and I sincerely hope you can help me

Hi, what can I do for you

**Comment by YangxinCs** [comment]
处理好的DDD测试集，可以私发我一份吗，论文会引用和感谢您

**Comment by yuanxiaoprc** [comment]
> 处理好的DDD测试集，可以私发我一份吗，论文会引用和感谢您

不行的，申请DDD数据的时候与英国那边签订了数据使用协议。
所以你可以自己去申请DDD数据，或者我们以合作的形式来使用这个数据，但是数据原则上还是不能外传。
